### ISSUE TITLE
Not sure how to assume policy

### ISSUE THREAD

**Issue by shoekstra** [oktadeveloper/okta-aws-cli-assume-role#122]
Hi,

In a previous version when I ran this tool I was prompted to select my okta role and then was presented a list of policies (aws roles) I could assume.

In the current version I can only choose the Okta role and there is no prompt for the role to assume - I presume this means I need to handle assuming the role myself?

**Comment by mrminecart** [comment]
Same where. okta seems to write the credentials into my .aws folder but doesnt set a default anymore.

**Comment by AlainODea** [comment]
@shoekstra I may not understand your use case properly as I couldn't get the old style integration working.

@mrminecart the lack of configuring default is frustrating. That's a separate concern from assuming policies, so please create another issue for it 😃 

The current version caches the mapping from profile name to role in an INI-formatted file at ~/.okta/profiles.

If you specify a profile that isn't in the file (not cached yet or manually deleted), it will prompt to select a role.

If you delete that file, it will prompt for roles again.

To assume a different policy or role than the ones bound from Okta to AWS, you will need to do an assume role yourself as the command. It no longer scans IAM and prompts as it used to. My thought at the time was that the design of the Okta Platform had changed to support directly assuming the destination role so that functionality wouldn't be needed. I am sorry it was lost in the transition.

**Comment by AlainODea** [comment]
@chris-whittick this is the issue you mentioned to me the other day. I think it's reasonably fixable.

**Comment by shoekstra** [comment]
> If you delete that file, it will prompt for roles again.

@AlainODea Is there a way to make it always prompt for role?

**Comment by shoekstra** [comment]
> To assume a different policy or role than the ones bound from Okta to AWS, you will need to do an assume role yourself as the command. It no longer scans IAM and prompts as it used to. My thought at the time was that the design of the Okta Platform had changed to support directly assuming the destination role so that functionality wouldn't be needed. I am sorry it was lost in the transition.

Thanks for clarifying, I suspected this was the case but couldn't find any mention of it.

**Comment by AlainODea** [comment]
@shoekstra does that resolve this issue for you?

**Comment by shoekstra** [comment]
Not sure if the PR does, but you've answered my question, thanks!
