### ISSUE TITLE
Feature Request: Support Multiple AWS App's

### ISSUE THREAD

**Issue by repl-mike-roest** [oktadeveloper/okta-aws-cli-assume-role#126]
We have multiple AWS accounts that we authenticate to through one Okta account but multiple AWS Apps.  It would be great to allow choice of AWS app similar to how the prompt for multiple roles works.

**Comment by AlainODea** [comment]
Interesting idea. I think this is achievable and it would make the minimal configuration org name-only which would make rollout easier.

On login the Okta web UI hits this endpoint:
`https://{{OKTA_ORG}}/api/v1/users/me/home/tabs?expand=items,items.resource`

It pulls down a structure like this:
```json
[
    {
        "// ... other properties we don't need for this": {},
        "_embedded": {
            "items": [
                {
                    "// ... other properties we don't need for this": {},
                    "_embedded": {
                        "resource": {
                            "// ... other properties we don't need for this": {},
                            "linkUrl": "https://{{OKTA_ORG}}/home/amazon_aws/AWS_APP_ID/AWS_APP_NUM",
                            "// ... other properties we don't need for this": {},
                        }
                    }
                }
            ]
        }
    }
]
```

A full, scrubbed example is linked here:
https://gist.github.com/AlainODea/e258213113039e6f94fadb6ed686575b#file-okta-user-tabs-json-L76

The algorithm is essentially this:
1. pull `https://{{OKTA_ORG}}/api/v1/users/me/home/tabs?expand=items,items.resource` as authenticated user
2. for each object:
3. for each _embedded.items:
4. for each _embedded.resource:
5. collect as candidate AWS app if linkUrl path starts with `/home/amazon_aws/`

This may not be 100% reliable.

@repl-mike-roest do all of your AWS app URLs paths start with /home/amazon_aws/? Mine do, but I want better assurance that it's not a coincidence.

Are you up for contributing this feature? If so, I can provide some guidance and code review.

**Comment by repl-mike-roest** [comment]
Hey @AlainODea ,
   I guess I jumped the gun a bit when I opened this request.  It looks like we're actually planning to have everything running under one App (we're still early in our Okta life) so looks like this isn't really required.  If we change our minds I'll open this back up and start working based on your direction.  Sorry.

**Comment by AlainODea** [comment]
No worries, @repl-mike-roest. Thank you for getting back to me. If you or your users have technical challenges adopting this, feel free to open issues and I'll try to help where I can.

**Comment by repl-mike-roest** [comment]
The _source credentials/configs issue is causing a bit of a headache for us with terraform as it doesn't seem to handle configs vs credentials I've written some batch files to help our users (just setting AWS_PROFILE=<profile>_source).  That seem to work on first glance.  As we move more into it if we run into issues I may come seeking help.

**Comment by AlainODea** [comment]
@repl-mike-roest we run into that too and use a similar workaround.

_source is an unfortunate workaround for a weird bug in the PowerShell SDK preventing the use of a profile if the credentials profile has the same name.

We couldn’t find a viable alternative for PowerShell. I’ll take a look and see if this bug is fixed in the AWS Tools for Windows PowerShell yet.

**Comment by repl-mike-roest** [comment]
Hmm maybe a property/environment variable for those of us who don't need the PowerShell compatibility? Would make things much simpler.

**Comment by AlainODea** [comment]
Just confirmed the bug (or maybe feature) of the AWS Tools for Windows PowerShell is still there: a ~/.aws/config profile with a source_profile of the same name is still not loadable.

I like the environment variable idea. Possibly **OKTA_SOURCE_PROFILE_SUFFIX**. It could default to **_source** if unset.

This is a fairly self-contained contribution. Are you willing to run with this?

In [OktaAWSConfig](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/OktaAwsConfig.java) you'd add code like this:

```java
getEnvOrConfigDefault(properties, "OKTA_SOURCE_PROFILE_SUFFIX", "_source"),
```

And define **getEnvOrConfigDefault** as follows:

```java
private static String getEnvOrConfig(Properties properties, String propertyName, String defaultValue) {
    String envValue = System.getenv(propertyName);
    return envValue != null ? envValue :
           properties.getProperty(propertyName, defaultValue);
}
```

Add a **sourceProfileSuffix** field to [OktaAwsCliEnvironment](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/OktaAwsCliEnvironment.java) to support it.

Alter **Configuration** to accept an **OktaAwsCliEnvironment** and use it's **sourceProfileSuffix** instead of the literal string `"_source"` here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/858511af382701a0d0a8481010e230d1c2c96125/src/main/java/com/okta/tools/aws/settings/Configuration.java#L71

Alter new instance creations of **Configuration** to supply **OktaAwsCliEnvironment**:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/858511af382701a0d0a8481010e230d1c2c96125/src/main/java/com/okta/tools/helpers/ConfigHelper.java#L46
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/858511af382701a0d0a8481010e230d1c2c96125/src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java#L55

Alter **Credentials** to accept an **OktaAwsCliEnvironment** and use it's **sourceProfileSuffix** instead of the literal string `"_source"` here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/858511af382701a0d0a8481010e230d1c2c96125/src/main/java/com/okta/tools/aws/settings/Credentials.java#L55

Alter new instance creations of **Credentials** to supply **OktaAwsCliEnvironment**:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/858511af382701a0d0a8481010e230d1c2c96125/src/main/java/com/okta/tools/helpers/CredentialsHelper.java#L44
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/858511af382701a0d0a8481010e230d1c2c96125/src/test/java/com/okta/tools/aws/settings/CredentialsTest.java#L46

**Comment by repl-mike-roest** [comment]
Yep I'll give it a whirl
