### ISSUE TITLE
Providing Access Across Multiple AWS Account via Okta

### ISSUE THREAD

**Issue by jpickeri93444** [oktadeveloper/okta-aws-cli-assume-role#135]
We are trying to consolidate all of our AWS account under one master account. We use Okta as a SSO solution. Seems quite simple and there are good instructions available (https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Amazon-Web-Service). But there seems to be a limit of 60 according to https://support.okta.com/help/Documentation/Knowledge_Article/Support-for-Multiple-Accounts-in-AWS.

As we have about 50 accounts now and expect to exceed 60 shortly, how can we over come this limit while still being able to provide SSO logins via Okta?

I am sure an Okta representative could answer this question, but our Okta account owner is currently unavailable to ask them.

Thanks.

Jim

**Comment by AlainODea** [comment]
This is technically possible, but involved.

It's out of the scope of this project to solve.

Pre-requisites:
1. Each group of 60 AWS accounts would need a distinctly named SAML Identity Provider
2. Each group of 60 AWS account would need a distinct Amazon Web Services Okta app
3. You would need different ~/.okta/config.properties for each or you'd need to contribute code for enumerating and providing a menu to select from multiple Amazon Web Service Okta apps 

Otherwise the IAM Roles and policies remain the same except for the changed Identity Provider ARN in the Trust Relationship policy.

You could replace 3 with a script that enumerates the apps, provides a menu, rewrites the config.properties, and then calls this code. Not elegant, but it would work.
