### ISSUE TITLE
Passwords with spaces break on the commandline

### ISSUE THREAD

**Issue by robkinyon-roivant** [oktadeveloper/okta-aws-cli-assume-role#140]
If I have a password with spaces, I have to put it into the config.properties. It does not work on the command line.

I'm specifically using Git-Bash on Windows, if that matters.

**Comment by AlainODea** [comment]
@robkinyon-roivant interesting. That's very strange. Using **OKTA_BROWSER_AUTH=true** in config.properties will move auth to a browser window which should side step this. Unfortunately it doesn't let you save your username.

I'll take a look at this.  I have a Windows VM I can test on.

**Comment by AlainODea** [comment]
@robkinyon-roivant I missed that your were using **OKTA_PASSWORD**.

IMPORTANT: **OKTA_PASSWORD** exposes your password in plaintext. It is intended only for experiments and debugging. Using it is a security risk.

I've reproduced your issue in setting passwords with leading or trailing spaces and having it not work when saved.

Due to the way Java Properties file are parsed, leading and trailing white spaces are stripped unless they are escaped.

A password with a leading space like `" my compromised password"`:

```
OKTA_PASSWORD=\ my compromised password
```

A password with a trailing space like `"my compromised password "`:

```
OKTA_PASSWORD=my compromised password\ 
```

A password with a leading and trailing space like `" my compromised password "`:

```
OKTA_PASSWORD=\ my compromised password\ 
```

IMPORTANT: **OKTA_PASSWORD** exposes your password in plaintext. It is intended only for experiments and debugging. Using it is a security risk.

**Comment by robkinyon-roivant** [comment]
@AlainODea Then, maybe the documentation should make that clear. Right now, the documentation says:
```
OKTA_PASSWORD is the password to use. If present will skip password input.
```
It says nothing about plaintext, security risks, or what the recommended set of configurations should be.

**Comment by AlainODea** [comment]
@robkinyon-roivant that's a very good idea. Do you want to write up the doc changes and submit a PR?

**Comment by robkinyon-roivant** [comment]
@AlainODea Given that I ran into this problem without knowing it was a problem and am asking the question, I don't think I'm the right person to write these changes up.

The point is I assumed that Okta would have treated passwords better than plaintext.

**Comment by AlainODea** [comment]
@robkinyon-roivant that's fair. I'll update the readme to actively discourage use of this feature.

Clarification: Okta (the service) handles your passwords securely in transit and at rest.

The security risk I highlighted is introduced by storing your password locally in a plaintext file or shell environment variable while using this tool. Any local process which has read access to **~/.okta/config.properties** or your shell environment variables can steal your password if you store it in either of those ways.

This may be an acceptable risk for you or it may not be.

The purpose of this tool is to replace permanent credentials stored in plaintext, with session-based, role-bound credentials, that expire relatively quickly. Saving your password, while convenient, largely defeats that purpose.

#171 recommends removing this feature entirely. I think I may proceed with doing that given the confusion around the security implications of keeping it.
