### ISSUE TITLE
Opens AWS Web Console instead of going back to shell

### ISSUE THREAD

**Issue by AlainODea** [oktadeveloper/okta-aws-cli-assume-role#152]
In certain cases, unknown cause right now. The Okta AWS CLI browser authentication window continues on to the AWS Web Console instead of switching back to the shell to pick a role.

Reported instances:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/136#issuecomment-408594220

**Comment by AlainODea** [comment]
This is part of the problem described in #120.

**Comment by AlainODea** [comment]
I can reproduce this. If using browser auth and the user has a single AWS role assigned by the Okta AWS app, then the web console is shown in the embedded browser window.

**Comment by AlainODea** [comment]
This is fixed on master, but broken in 1.0.2. A release will fix this.

**Comment by AlainODea** [comment]
@loopingz this is the master issue for embedded browser launching the web console instead of switching back. This is fixed on master for me. If you can reproduce this issue on master, please let me know.

**Comment by JonathanCooper** [comment]
@AlainODea Do you have a release schedule?  Just wondering when this fix is likely to make it into a release.

**Comment by mraible** [comment]
I'm back from vacation, and happy to do a release. Here's what I've done in the past:

1. Update local source from master.
2. Change `pom.xml` to have release number. Commit and push.
3. Run `mvn package`.
4. Create release on GitHub and upload JAR.
5. Change `pom.xml` to have next release number. Commit and push.

I'm not sure we need releases since folks can do this on their own and it's not an "official" Okta project.

**Comment by loopingz** [comment]
I think we need to do a release. I think there are several customers of this project even if this is not an 'official' Okta project. I would myself would probably not use Okta anymore if this tool was not around.

It would be great to remove the binaries as describe on ticket #127 before doing the release.

**Comment by mraible** [comment]
Fixed in 1.0.3 release (happening now).
