### ISSUE TITLE
Inherit the session duration setting from the SAML sign-on config

### ISSUE THREAD

**Issue by adamdamico** [oktadeveloper/okta-aws-cli-assume-role#16]
For federated cross-account cases, we can now get sessions longer than 1 hour in the web console (as of 2016.46/47), but this tool is still only handing out 1-hour sessions. It should inherit the setting of the app instance.

**Comment by adamdamico** [comment]
Just realized there's a closed issue for this same request, but I'm still pretty confused as to why there isn't (or can't be) parity in the functionality.

**Comment by raphaellondner-okta** [comment]
@adamdamico As mentioned in the previous, closed issue, this is because AWS currently only allows 12hour-long sessions when you log in directly into the AWS Console (and that has nothing to do with the app instance/SAML attribute), but it's not yet available at the API level.

I actually talked with a Product Manager of AWS IAM at AWS re:Invent and she told me AWS is acutely aware of the feature discrepancy between the AWS console and the AWS API and are working to make this available at some point in 2017 (no ETA available, sorry).

Soon after this becomes available, we should able to make that very simple one-liner change (cf. https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/awscli.java#L421 - the comment is actually wrong right now)
