### ISSUE TITLE
aws sts caller identity issue

### ISSUE THREAD

**Issue by jeugene** [oktadeveloper/okta-aws-cli-assume-role#199]
**Describe the bug**
Execute below after executing the okta cli code that generates the temp keys
aws sts get-caller-identity (this executes aws cli code) and retursn below
"Arn": "arn:aws:sts::123123123:assumed-role/role-name/botocore-session-123123123"

The generated session "botocore-session-123123123" does not work with policy userId or saml iam policy variables
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html

A possible solution is "role_session_name" from saml assertion in config file but this does not work entirely. The real session identifier is the "Federated Login: role/userId" in AWS web console.

Setting AWS_ACCESS_KEY_ID and other environment variables from okta cli saml response manually and executing "aws sts get-caller-identity" and tests with AWS IAM policy variables does work.
It does NOT work with using profile in ~/.aws/config and ~/.aws/credentials

I am trying to find the root cause and solution.

Can someone help clarify why docs state to call "sts get-caller-identity" like below and is this doing something with the aws session identifier?

Usage
aws test sts get-caller-identity

**Comment by jeugene** [comment]
I have confirmed the Usage docs process below does NOT work correctly with AWS IAM policy variables.
USAGE : https://github.com/oktadeveloper/okta-aws-cli-assume-role#usage

Not clear why Okta cli code is trying to control AWS CLI? These should be independent/decoupled and not interfere with each other.

The saml response credential keys work by manually setting them as environment variables. This automatically gets the right AWS Session. The okta cli creds in config, credentials file do not work.

Any ideas anyone?

**Comment by AlainODea** [comment]
This is an interesting problem. Thank you for reporting it.

It sounds like you are trying to use the default profile. That can work but you need to run this tool as **aws default ...** where ... is the AWS CLI subcommand if you intend to use the default profile.

This tool updates the ~/.aws/credentials and ~/.aws/config files with named profiles. You’ll need to refer to the profiles by name when using tools like **aws** for them to work. By design it sets up the profile (or environment variables if OKTA_ENV_MODE=true) and calls the downstream command as a sub-process.

**sts get-caller-identity** is like **whoami**. It’s intended to be the most basic possible check that the AWS Okta integration is working.

When you run **aws test sts get-caller-identity** from the example it is intended to use the **aws** shell function to wrap the call to the real AWS CLI’s **aws** executable. That shell function sends in the profile name as an environment variable (**OKTA_PROFILE=test**) and as a program argument (**--profile test**).

If you are on macOS or Linux you should be able to run the AWS CLI directly (bypassing the shell function), by running **env aws** like **env aws --profile test sts get-caller-identity**.

**Comment by AlainODea** [comment]
> Not clear why Okta cli code is trying to control AWS CLI? These should be independent/decoupled and not interfere with each other.

The Okta CLI code controls the AWS CLI (or other downstream program) by design. Wrapping a downstream command is the central intent of this tool.

The decoupling you describe is an interesting alternative way of looking at this. I’m open to creating an entry-point that does not run any downstream command if you think it would be useful to you.

**Comment by AlainODea** [comment]
The generated session **botocore-session-123123123** is the role session name that the AWS CLI creates when it assumes the role using the credentials this tool obtains from AWS STS. The sts get-caller-identity response is not usable as AWS credentials.

You could run this tool like **aws test s3 ls** to list your S3 buckets (if the role you gave it in Okta allows that).

The AWS CLI named profile will have a different name.

You should see something like this in ~/.aws/config:

```
[profile test]
source_profile=test_source
...
```

And in ~/.aws/credentials:

```
[test_source]
aws_access_key_id=...
aws_secret_access_key=...
aws_session_token=...
...
```

**Comment by jeugene** [comment]
Thanks for the reply @AlainODea 
I've fixed the issue on my side. The issue bit rooted in this code 

Let me clarify. 

**Problem statement**
1. AWS CLI Command -> aws s3 cp test.txt s3://bucket/tmp/**johndoe12345**/
2. **johndoe12345** is an AWS IAM policy variable. User personal partition s3 space
3. **johndoe12345** is able to upload file via AWS Console Web UI
4. **johndoe12345** is NOT able to upload files via Okta CLI after running through OKTA - error upload denied
*Debug the issue*
1. After debugging Okta CLI, get the saml response for aws access, secret and token and hard set them as environment variables and whola.. this works
2. This indicates that all the Okta write into .aws/* files does NOT work with regular AWS CLI for this case. This is the _source and arn stuff in configs
3. Okta CLI keys corrupt AWS CLI regular request for this case (including caller identity)

*Solution*
- Remove the Okta write into .aws/*. Then pass keys to out to bash and set them
- AWS CLI now works with IAM policy variables

Please confirm if there is better solution.

**Comment by AlainODea** [comment]
Okay. I think I understand your use case way better now. This is a really interesting use case and opens a bunch of possibilities for how we could use this at work.

If I read you correctly, you are using [IAM Policy Variables](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html), likely referencing **aws:userid** in those policies to dyanmically constrain access to resources like subkeys (akin to sub-folders) in S3. I’m trying to think why the role session name isn’t set to the Subject NameID in the SAML assertion already.

OKTA_ENV_MODE=true should let you write just the AWS credentials envvars your downstream commands need with the appropriate role session name. With that enabled it will not update the ~/.aws/... files. The command you run to get credentials could be this:

```bash
#!/bin/bash
echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
```

That would echo the environment for source-ing into the shell environment similar to how **ssh-agent** works.

Would that work? If so, I can pretty easily make an entry-point that does this. I might make it operate like a credentials_process (emitting JSON instead of Bash script) for integration reasons.

**Comment by AlainODea** [comment]
This is an incredibly cool use case. I’m excited to start experimenting with this :)

**Comment by AlainODea** [comment]
#203 may also be interesting to you. It adds a **CredentialProcess** entry point that produces a JSON output matching what the AWS CLI expects:
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes

This allows for other processes to call this tool for credentials and get back a data structure they can use as they please.

**Comment by jeugene** [comment]
> If I read you correctly, you are using IAM Policy Variables, likely referencing aws:userid in those policies to dyanmically constrain access to resources like subkeys (akin to sub-folders) in S3. I’m trying to think why the role session name isn’t set to the Subject NameID in the SAML assertion already.

There are multiple IAM policy variables for regular login and federated login. All of them need to work consistently. Injecting role_session_name works for the case you reference above, but does not work for other IAM policy variables.

> #!/bin/bash
> echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
> echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
> echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"

The above only works for the "current" terminal session. The context is lost in *new* terminal session

**Comment by jeugene** [comment]
> That complicates things as aws:userid is not okta.user@example.com, it's more like AROAABCDEFGHIJKLMNOPQ:okta.user@example.com:
> 
> AROAABCDEFGHIJKLMNOPQ is the role id determined by AWS on IAM Role creation
> okta.user@example.com is the caller-specified-role-name determined by Okta based on the Application username format set on the Amazon Web Services Okta app in your Okta  org
> 
The saml response is "okta.user@example.com" is because this that is the configuration in okta

"AROAABCDEFGHIJKLMNOPQ:okta.user@example.com:"

That is the roleId and saml subject. We are not using above method. To make "only" above solution work, inject "role_session_name" in okta configs and it will work.

However, the above process is buggy and will not work for all IAM policy variables use cases.

**Comment by jeugene** [comment]
The solution that works for *all* IAM policy use cases, multiple terminals is below.
- Remove code in ConfigHelper.java
- Remove code in CredentialsHelper.java
- Get the saml response AWS keys (access, session and token) from the Okta cli code response in awscli.java
- Simulate either below or this expected result of this
https://docs.aws.amazon.com/cli/latest/reference/configure/set.html
- Set AWS keys (access, session and token) exactly how "aws configure" command works

I disabled the Okta code writing into ~/.aws/* and replaced with "aws configure" expected result and everything works for various IAM policy permutations.

The other issue referenced is to modify FileHelper.java  and reader/writer is not useful as the change i made to make it work disables all write into ~/.aws/*. 

Hope above clarifies the solution

**Comment by AlainODea** [comment]
Regarding https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/199#issuecomment-420833015:

This tools is designed to work with the multi-account multi-role configuration using Okta’s integrated Amazon Web Services app in SAML mode.

I think you’re on to something with the **aws configure** approach. That would remove a lot of special handling code for AWS config files this tool doesn’t own.

Can you publish a pull request with your changes?

**Comment by jeugene** [comment]
Thanks @AlainODea 
Above is accurate. We have multiple aws accounts and many roles. We continuously swap in and out roles for various AWS role specific isolated privileges. This usage works well with the above solution. I'll publish the PR.

**Comment by davidsuehring** [comment]
@jeugene Do you have an update on your PR for this? I'm glad I looked in here, as we were running into these issues with a similar use case, and starting to look into options to resolve it!

@AlainODea Out of curiosity, is there use case that I'm missing that causes the tool to need to write the role to .aws/config at all? Providing the source_profile and role_arn options in that file tells the AWS CLI to assume that role as the first action after authentication, but aren't those credentials already for that role (which is why the docs call out the need to add a policy for the role to assume itself)? Is there a time where the role written in config wouldnt be the same as the role we received credentials for?

**Comment by AlainODea** [comment]
@davidsuehring 

>is there use case that I'm missing that causes the tool to need to write the role to .aws/config at all?

This is a legacy thing. It was in the original implementation. I think you are right, assuming that the AWS CLI can work without a profile defined in ~/.aws/config.

> Providing the source_profile and role_arn options in that file tells the AWS CLI to assume that role as the first action after authentication, but aren't those credentials already for that role (which is why the docs call out the need to add a policy for the role to assume itself)?

Good catch! I didn't realize setting **role_arn** behaved like that. That's likely the root cause here and is an easy fix. I can also remove that weird IAM policy advice from the readme.

Re-reading this you have got this right:
https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

I think I can remove the writes to ~/.aws/config entirely and it will still function and function better than before.

I'll give this a try this week.

**Comment by davidsuehring** [comment]
@AlainODea Awesome, thanks for the explanation! As I was thinking through this a little more, the piece of data that probably still needs to be in .aws/config is "OKTA_AWS_REGION", because I don't think that is supported in the credentials file. So, that might be something to watch out for.

**Comment by AlainODea** [comment]
@davidsuehring you are 100% right here.

@jeugene your suggested fix (removing the writes to ~/.aws/config) from before worked. I didn't understand initially.

This fixes a lot of ugliness in this tool. I have to test my solution with PowerShell to make sure it still works there. I suspect this will solve the problem implicitly.

You are both solid, helpful folks for sticking with this. Thank you.

**Comment by AlainODea** [comment]
@davidsuehring yes, region is a potential snag. I think I may document that and leave it for users. Separate this tool entirely from the AWS config as @jeugene suggested. He’s right, it has no business fiddling with it.

**Comment by AlainODea** [comment]
@jeugene v1.0.4 is released with a fix for this.
