### ISSUE TITLE
Way to override session to not use botocore-session-123456789

### ISSUE THREAD

**Issue by pc-mreeves** [oktadeveloper/okta-aws-cli-assume-role#205]
Currently the session uses a string like botocore-session-GUID. It would be better to be able to override that with `whoami` or the Okta user or ANYTHING to make things like auditing in cloudtrail easier.

Maybe the GUID is actually a timestamp. anyways...

Now:
```
aws sts get-caller-identity
{
    "UserId": "AROAABCDEFABCDEFABCDEF:botocore-session-$GUID",
    "Account": "REDACTED",
    "Arn": "arn:aws:sts::REDACTED:assumed-role/SAML-MyRole/botocore-session-$GUID"
}
```

Better:
```
aws sts get-caller-identity
{
    "UserId": "AROAABCDEFABCDEFABCDEF:pc-mreeves-$GUID",
    "Account": "REDACTED",
    "Arn": "arn:aws:sts::REDACTED:assumed-role/SAML-MyRole/pc-mreeves-$GUID"
}
```

**Comment by jeugene** [comment]
The hack solution is modify "OktaAwsCliEnvironment.java" and add role_session_name value from okta saml response.

The above does not solve majority fo the use cases.. the details are in below issue.

https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/199

**Comment by AlainODea** [comment]
**OKTA_ENV_MODE** is designed to work for a single command. It sets the process environment for the subprocess that WithOkta or awscli launches. It is intended for use cases where credentials are not allowed to be stored at rest.

**Comment by AlainODea** [comment]
**OKTA_ENV_MODE** does work across multiple terminals if you use withokta or the installer-provided aws shell function since it will go through Okta for fresh credentials each time.

There appears to be a bug in how this tool sets up the config and credentials files. The AWS CLI should be able to directly use the provided session with an STS:AssumeRole operation, but for some reason it does one if used in the mode where config and credentials are written.

@jeugene’s proposed solution using **aws configure** to populate those files is a promising complete solution to persistent named profile support with proper IAM Policy Variables support.

**Comment by AlainODea** [comment]
Viable alternative proposed. No response in a while, so I'm closing this.

**Comment by AlainODea** [comment]
@pc-mreeves v1.0.4 is released with a fix for this.

**Comment by pc-mreeves** [comment]
@AlainODea - Sorry, what is the fix? Is there an env var to manipulate or will the session automatically use a user's name or...? Sorry for late reply, I lost this thread in my gigantic inbox...

**Comment by AlainODea** [comment]
@pc-mreeves #211 removes the superfluous assume role triggerred by writing source_profile and role_arn as described here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/199#issuecomment-424512585

Since that no longer happens the role session has a predictable name based on the IAM role ID and username Okta sends.
