### ISSUE TITLE
profile names in ~/.aws/config and ~/.aws/credentials file are not compatible with AWS Java SDK V2

### ISSUE THREAD

**Issue by jpollard-cs** [oktadeveloper/okta-aws-cli-assume-role#208]
please see discussion here: https://github.com/aws/aws-sdk-java-v2/issues/389#issuecomment-421195380

**Comment by AlainODea** [comment]
Related to #157.

Do you have a stacktrace for the failure you are encountering? If not, can you describe it in as much detail as possible?

**Comment by AlainODea** [comment]
The issue you describe is due to the legacy generate profile name behavior if **OKTA_PROFILE** is unset. I don't recommend using this tool without it. The installer sets up an **aws** wrapper shell function that takes the profile name as it's first argument and otherwise acts like the true AWS CLI's **aws** program.

Make sure to set the **OKTA_PROFILE** environment variable or configuration property to something. It's the name of the profile to use.

**Comment by jpollard-cs** [comment]
hey @AlainODea the company I'm working with has me using a very specific version of the SDK - I believe this was due to an issue where the okta-aws-cli tool stopped listing role policies. Does that issue sound familiar? Either way I'll give the latest tool a shot. Also browsing for related issues I stumbled upon the `OKTA_ENV_MODE=true` - that might help me avoid this issue, as well 😄

**Comment by jpollard-cs** [comment]
thanks @AlainODea - it looks like there's another issue at play here regarding our IAM role design being incompatible with more recent changes so I think for now I'm going to fork the repo, rollback to the revision that works for us (58951777a9893f53c38a5c10848b22f469098669) and transplant the `OKTA_ENV_MODE=true` functionality into that

**Comment by jpollard-cs** [comment]
reopening as I noticed there was an action item coming out of https://github.com/aws/aws-sdk-java-v2/issues/389#issuecomment-421229658

**Comment by AlainODea** [comment]
@jpollard-cs v1.0.4 is released with a fix for this.
