### ISSUE TITLE
Powershell installation script and the readme file are at odds with each other

### ISSUE THREAD

**Issue by testworksau** [oktadeveloper/okta-aws-cli-assume-role#242]
The readme indicates that the default value of `OKTA_BROWSER_AUTH` is false:

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/Readme.MD#configuring-the-application

The powershell script sets this to true:

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/3b1bdaba73fae8ee88b3795b2e4df31d61acb13a/bin/Install-OktaAwsCli.ps1#L42

I am happy to create a pull request to fix the readme or the powershell script; I just need to know which one is right.

**Comment by AlainODea** [comment]
@testworksau good catch. This is a weird one. They're both right.

When running the program itself without **OKTA_BROWSER_AUTH** set in environment or **config.properties**, it defaults to **false**.

The installer sets up a **config.properties** with **OKTA_BROWSER_AUTH** set to **true**. This was a workaround for some issues with MFA options that don't work from the CLI.

I'm not sure how to resolve this in a good way.

**Comment by AlainODea** [comment]
The documentation describes the defaults without any settings in ~/.okta/config.properties. The documentation is correct. The installer overrides the default to use OKTA_BROWSER_AUTH true, because it is a better out of the box option since it supports more of Okta's authentication policy features.

I'm sorry you are still confused here. I have no good path forward, so I'm going to close this issue.
