### ISSUE TITLE
Unable to get ACCESS_KEY/TOKEN env

### ISSUE THREAD

**Issue by rajeshpks** [oktadeveloper/okta-aws-cli-assume-role#270]
**Describe the bug**
My configs
OKTA_ORG=xxx
OKTA_AWS_APP_URL=xxx
OKTA_USERNAME=xxx
OKTA_BROWSER_AUTH=false
OKTA_ENV_MODE=true

when i Run okta-aws test sts get-caller-identity
It always pops up an java UI to login to AWS. After I login, i need the  AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN env vars set in my terminal.
How to achieve this please?

**Comment by AlainODea** [comment]
OKTA_ENV_MODE means that this tool runs the downstream command with those environment variables set. You need to run a shell as the downstream command to get the effect you want.

Use withokta to run bash instead of aws CLI. The profile name isn’t used, so I set it to ignored:

```bash
withokta ignored bash
```

Or create this file on you PATH which you can run as okta-bash:

```bash
#!/bin/bash
env OKTA_ENV_MODE=true java \
    -Djava.util.logging.config.file=~/.okta/logging.properties \
    -classpath ~/.okta/okta-aws-cli.jar \
    com.okta.tools.WithOkta $command bash $@
```

**Comment by AlainODea** [comment]
You should not be prompted by AWS to Assume Role or Obtain Credentials. That's not a prompt this tool can handle. The AWS web UI should never be displayed by this tool. If it is, you won't be able to get credentials.

I had a typo there. I should not have included $command.

Try this:

```bash
#!/bin/bash
env OKTA_ENV_MODE=true java \
    -Djava.util.logging.config.file=~/.okta/logging.properties \
    -classpath ~/.okta/okta-aws-cli.jar \
    com.okta.tools.WithOkta bash $@
```

**Comment by rajeshpks** [comment]
Thanks for your reply. My bad I had OKTA_BROWSER_AUTH=true hence the browser window was popping up. After make this false, the okta login is happening in terminal. However I am facing issue with app URL.
Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : Okta Verify (Push)
[ 2 ] : SMS Verification
[ 3 ] : Okta Verify (TOTP)
Selection: 1

Push Factor Authentication
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
Waiting for you to approve the Okta push notification on your device...
20111RVCH5vKhyMA8qs4R-IKBLaEmFOu1Z1cVFX6erszykgcB853uEV
Exception in thread "main" com.okta.tools.saml.OktaSaml$PromptForFactorException: Unsupported App sign on rule: 'Prompt for factor'. 
Please contact your administrator.
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsFromDocument(OktaSaml.java:71)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:57)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:50)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:130)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
Can you please help me understand the error? I can modify defect description if needed. Thanks.

**Comment by AlainODea** [comment]
App-level MFA requires OKTA_BROWSER_AUTH=true to work. The Okta AuthN API doesn’t expose the prompts for it, so you need a browser to present them.

Can you provide some screenshots of what you see with OKTA_BROWSER_AUTH=true enabled?

**Comment by ckizziar** [comment]
@AlainODea Hey Alain, first of all thank you for all of your contributions to this tool, you've made up for a tremendous amount of support that's sadly lacking from Okta themselves.

I enabled OKTA_BROWSER_AUTH just to test your method both ways, and on my end running the script, just replacing bash with zsh for my case, works without app-level MFA. The `withokta ignored zsh` however does not, it just complains about the profile name not being a valid command. No biggie for me, just an FYI. I actually wrote a probably way-too-complicated script myself to export environment variables for a session, including checking whether the profile had been set, renewing the token, etc. But it seems that the ~/.okta/profiles expiry is the Okta session not the STS token, so that part doesn't really seem to work. The biggest benefit to that approach, at least in my opinion, was the fact that it didn't spawn endless sub-shells within sub-shells. From what I gather, running the script multiple times to switch roles, will just keep digging deeper into zsh/bash sub-shells that then need to get exited out of, or am I wrong on that?

Either way, here's a little edit I made to your script, aside from the purely personal use of zsh, this lets me run the command with a profile parameter, so that I don't have to pick my role every time I run it, so long as it's been used before.

```bash
 #!/bin/zsh
 env OKTA_ENV_MODE=true OKTA_PROFILE=$1 java \
         -Djava.util.logging.config.file=~/.okta/logging.properties \
         -classpath ~/.okta/okta-aws-cli.jar \
         com.okta.tools.WithOkta zsh
```

**Comment by AlainODea** [comment]
> @AlainODea Hey Alain, first of all thank you for all of your contributions to this tool, you've made up for a tremendous amount of support that's sadly lacking from Okta themselves.

@ckizziar my pleasure. Thank you.

> I enabled OKTA_BROWSER_AUTH just to test your method both ways, and on my end running the script, just replacing bash with zsh for my case, works without app-level MFA.

That's good to hear.

> The `withokta ignored zsh` however does not, it just complains about the profile name not being a valid command.

I think you might be using [bin/withokta](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/bin/withokta). That is an unusable legacy thing. I should remove it. I intended for you to use the [withokta which install.sh creates](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/57d550cd5cd83ef07b0e9943ff6c6db5f9ce3e83/bin/install.sh#L134-L142).

> No biggie for me, just an FYI. I actually wrote a probably way-too-complicated script myself to export environment variables for a session, including checking whether the profile had been set, renewing the token, etc.

Complicated or not, this script sounds really useful. Are you willing to contribute it?

> But it seems that the ~/.okta/profiles expiry is the Okta session not the STS token, so that part doesn't really seem to work.

This is an interesting observation. I think you are right. I'll investigate that.

> The biggest benefit to that approach, at least in my opinion, was the fact that it didn't spawn endless sub-shells within sub-shells. From what I gather, running the script multiple times to switch roles, will just keep digging deeper into zsh/bash sub-shells that then need to get exited out of, or am I wrong on that?

okta-bash/okta-zsh/okta-fish are intended to be used like bash, zsh, or fish. Invoking them within an existing session will create subshells. Here's my workflow (which avoids that):

```shell
$ okta-fish arn:aws:iam:000000000000:role/EC2Admins
~> aws ec2 ...
~> exit
$ okta-fish arn:aws:iam:000000000000:role/S3Admins
~> aws s3 ...
~> exit
$ okta-fish arn:aws:iam:111111111111:role/EC2Admins
~> aws ec2 ...
~> exit
```

> Either way, here's a little edit I made to your script, aside from the purely personal use of zsh, this lets me run the command with a profile parameter, so that I don't have to pick my role every time I run it, so long as it's been used before.
> 
> ```shell
>  #!/bin/zsh
>  env OKTA_ENV_MODE=true OKTA_PROFILE=$1 java \
>          -Djava.util.logging.config.file=~/.okta/logging.properties \
>          -classpath ~/.okta/okta-aws-cli.jar \
>          com.okta.tools.WithOkta zsh
> ```

That's a great addition. Thank you for sharing it.

Here's a variant that can take an IAM Role ARN:
```zsh
#!/bin/zsh
env OKTA_ENV_MODE=true OKTA_AWS_ROLE_TO_ASSUME=$1 java \
         -Djava.util.logging.config.file=~/.okta/logging.properties \
         -classpath ~/.okta/okta-aws-cli.jar \
         com.okta.tools.WithOkta zsh
```

This command will get you a list of account aliases and role ARNs you can use for the command above:
```shell
okta-listroles | jq '.[] | "\(.accountName): \(.roleOptions[].roleArn)"' --raw-output | awk '{print $2 ": " $4}'
```

**Comment by ckizziar** [comment]
> I think you might be using [bin/withokta](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/bin/withokta). That is an unusable legacy thing. I should remove it. I intended for you to use the [withokta which install.sh creates](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/57d550cd5cd83ef07b0e9943ff6c6db5f9ce3e83/bin/install.sh#L134-L142).

@AlainODea Yeah, the last few releases I've just replaced the jar, so that would explain that. I'll do a proper update, and fix that in my script too (it's using the same, might explain some quirks I've run into).

> Complicated or not, this script sounds really useful. Are you willing to contribute it?

Absolutely, just be forewarned I'm still fairly new to bash/zsh/linux scripting so I'm sure it's rather amateur and can use a lot of refinement. I have it up in a [Gist](https://gist.github.com/ckizziar/a60a84a6a148a8fd7b0ef536409352d3) at the moment, let me know if you'd like me to contribute it some other way. Any way I can be of help and give back, I'm definitely up for doing whatever I can.

As for the STS token expiration, I'm going to continue digging into that one as well, my research so far hasn't led me to finding the actual STS token's expiration time anywhere, short of trying to execute a CLI call and being told the token has expired.

I'm going to turn in for a few hours of sleep, but I'll try to update to the new withokta tomorrow and get the script updated with that change.

**Comment by AlainODea** [comment]
I’m going to assume this is resolved.
