### ISSUE TITLE
Escape the use of Okta (or allow app URL switch) for a given account

### ISSUE THREAD

**Issue by philliphayesiam** [oktadeveloper/okta-aws-cli-assume-role#275]
The following might already be supported, so this may just be more of an inquiry for help

**Is your feature request related to a problem? Please describe.**
We're in a multi AWS account environment where we like to run scripts against all aws accounts by looping through the okta profiles.  This gets tricky however with GovCloud because it is a separate URL

**Describe the solution you'd like**
Either provide a way to programmatically escape the use of okta (and use good old fashioned issued aws access keys from the .aws/credentials file) or allow for the change of the APP URL programmatically (maybe passed as parameters to okta-cli??)

**Describe alternatives you've considered**
Running independent reports for GovCloud based AWS accounts vs. "Regular/Public" AWS accounts

**Additional context**
None

**Comment by AlainODea** [comment]
> The following might already be supported, so this may just be more of an inquiry for help

This is solvable without code changes.

> **Is your feature request related to a problem? Please describe.**
> We're in a multi AWS account environment where we like to run scripts against all aws accounts by looping through the okta profiles. This gets tricky however with GovCloud because it is a separate URL

OKTA_AWS_APP_URL is what needs to change between the environments I believe. It should otherwise work.

> **Describe the solution you'd like**
> Either provide a way to programmatically escape the use of okta (and use good old fashioned issued aws access keys from the .aws/credentials file) or allow for the change of the APP URL programmatically (maybe passed as parameters to okta-cli??)

If you run the AWS CLI directly, it uses the credentials file without going through this tool first.
If you set the environment variable **OKTA_AWS_APP_URL** in your shell, it overrides the setting in ~/.okta/config.properties.

> **Describe alternatives you've considered**
> Running independent reports for GovCloud based AWS accounts vs. "Regular/Public" AWS accounts
> 
> **Additional context**
> None

Here's a worked solution:

```shell
okta-aws acct1 sts get-caller-identity
okta-aws acct2 sts get-caller-identity
okta-aws acct3 sts get-caller-identity
export OKTA_AWS_APP_URL=https://example.okta.com/home/amazon_aws/0oa1234567890abcd1t7/123
okta-aws acct4 sts get-caller-identity
aws --profile acct1 ... # aws sub-commands for acct1
aws --profile acct2 ... # aws sub-commands for acct2
aws --profile acct3 ... # aws sub-commands for acct3
aws --profile acct4 ... # aws sub-commands for acct4
```

The **okta-aws {profile_name} sts get-caller-identity** steps set up profiles in ~/.aws/credentials for each account or role you need. For GovCloud accounts/roles, you set the OKTA_AWS_APP_URL environment variable and then run **okta-aws {profile_name} sts-get-caller-identity** and it also sets up that profile in ~/.aws/credentials.

**Comment by AlainODea** [comment]
@philliphayesiam any luck trying this?

**Comment by philliphayesiam** [comment]
This was perfect.  thank you!
