### ISSUE TITLE
Documentation needs to be updated to reflect [default] profile usage

### ISSUE THREAD

**Issue by ryangood** [oktadeveloper/okta-aws-cli-assume-role#44]
We ran into an issue where one of our developers had [default] profile credentials already setup in the aws credentials file. Nowhere in your documentation did we see that these would be overwritten.

**Comment by boyvanduuren** [comment]
I ran into this as well.
The following text really threw me off my guard:
> To use these credentials, please call the aws cli with the --profile option (e.g. aws --profile 421<snip>m/0 ec2 describe-instances)

This lead me to believe my default role was kept intact, even though it was overwritten with the same data as the profile that was just created.

I'd really hate for someone to accidentally throw away important resources due to this. I'm willing to spend some time to fix this if my PR is welcome.

**Comment by rdegges** [comment]
I'm happy to accept PRs here. We don't have an active maintainer atm, and I'm not a Java guy, but I'd be more than happy to merge fixes in to keep things chugging along.

**Comment by AlainODea** [comment]
Sorry for this, @ryangood. This has been fixed now.

The current implementation does not overwrite the default profile.

@mraible I think it's safe to close this issue now :)
