### ISSUE TITLE
Allow user to pick default region

### ISSUE THREAD

**Issue by wonderphil** [oktadeveloper/okta-aws-cli-assume-role#46]
Hi guys,

Is there any way to allow user to pick the region that is populated in the config file?

if not anyway we can get it added to the config.properties ?

Thanks

**Comment by AlainODea** [comment]
@smashling is working on named profile support now. I'm hoping he'll have a PR ready for release next week. Named profiles would let you handle persistent configuration options like region. I'll ask him to factor in testing of updating an existing profile and see if it can preserve existing properties.

**Comment by AlainODea** [comment]
@smashling this will require fixing the bug I introduced by hardcoding the region here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/54db0bfa82f108457d893459b0b40eafaa669236/src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java#L232-L236

**Comment by AlainODea** [comment]
@smashling there's a bug in profile management that impacts region selection.

The profile management introduced in #81 (merged to **master**) overwrites the **region** in **~/.aws/config**. If a region is in the file, it should leave it untouched. The bug predates that functionality, but was harmless since the original code would create fresh profiles each time. Multi-profile support highlights the need to check for existing profile keys (like **region**) and avoiding overwriting them where possible.

The tool also creates or updates the **source_profile** field within that config profile and create or update the referenced credentials profile in **~/.aws/credentials**. I'm not sure if there's a good way around overwriting **source_profile** as it would greatly complicate credential profile management.
