### ISSUE TITLE
awscli results in `aws' command error, no credentials

### ISSUE THREAD

**Issue by dlgoodr** [oktadeveloper/okta-aws-cli-assume-role#75]
```
$ ./awscli
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
$
```

config.properties contains ```OKTA_ORG``` and ```OKTA_AWS_APP_URL```.  I was prompted once for credentials but removed the credential file to test something.  Ever since then I haven't been prompted for auth on run of the jar, and ```~/.aws/credentials``` is not repopulated.  Repo cloned and built Feb 2, approximately 11:30 AM CST.  Don't know if there's a 'stable' branch I should be cloning instead or if there's a known defect.

**Comment by AlainODea** [comment]
That’s due to my design change. awscli nows runs the aws command line with the arg list handed to it, after creating a profile session. Try running this:

```bash
./awscli sts get-caller-identity
```

That will run aws sts —profile {generated-profile-name} get-caller-identity after you authenticate.

You may find using the withokta command (available on master) with OKTA_PROFILE env set to be a useful alternative. It acts more like sudo and will run whatever command you specify literally instead.

```bash
env OKTA_PROFILE=prod ./withokta aws —profile prod sts get-caller-identity
```

You can integrate with any downstream command that uses named profiles, including things like Serverless and Terraform.

**Comment by AlainODea** [comment]
Not be re-prompted and not having the credentials file update is definitely a bug.

**Comment by AlainODea** [comment]
The **master** branch is the most stable release. We're incrementally fixing issues and improving the user experience.

**Comment by dlgoodr** [comment]
should a present `~/.okta-aws-cli-session` and absent `~/.aws/credentials` be a condition the app detects and resolves?  It's not behavior people accustomed to the traditional aws-cli would expect.

**Comment by AlainODea** [comment]
@dlgoodr I have a fix coming for that. It actually solves a first run problem as well. If you install AWS CLI and this tool without running aws configure, the same crash happens. Good catch!

**Comment by dlgoodr** [comment]
:+1:
