### ISSUE TITLE
Update documentation in Okta Help Center

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-aws-cli-assume-role#93]
Hello @AlainODea! Can you please tell me what needs to change in https://support.okta.com/help/Documentation/Knowledge_Article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta so it's up-to-date with this repo?

**Comment by AlainODea** [comment]
Sure thing. @smashling is preparing a getting started presentation, so in that process I'll review the Okta Help Center material and suggest updates as well.

Thank you, @mraible :)

**Comment by AlainODea** [comment]
Sorry for the delay on this. @smashling can you take a look at the docs and provide some recommendations by Tuesday next week?

**Comment by smashling** [comment]
In the Part 2:Use the Token section, I would add a note about the new command for users with multiple profiles that they switch between. An example command would be end OKTA_PROFILE=[profile name] withokta aws --profile [profile name] s3 ls. I would also recommend that the user makes a command alias for their various profiles, because of how long the current command is.

**Comment by AlainODea** [comment]
@mraible my readme updates in #146 and the corresponding installer scripts should dramatically help ease of adoption for this tool.
